---
title: "Geography 176A"
author: "[Kyler Plouffe](https://kplouffe.github.io/kplouffe/)"
subtitle: 'Lab 03: Distances and the Border Zone'
output:
  html_document:
    theme: journal
---

```{r}
# SPDS
library(tidyverse)
library(sf)
library(units)

# Data
library(USAboundaries)
library(rnaturalearth)

# Visualization
library(gghighlight)
library(ggrepel)
library(knitr)
```

### Question 1
```{r}
#1.1
eqdc = '+proj=eqdc +lat_0=40 +lon_0=-96 +lat_1=20 +lat_2=60 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs'

#1.2
conus = USAboundaries::us_states(resolution="low") %>%
  filter(!state_name %in% c("Puerto Rico",
                            "Alaska",
                            "Hawaii")) %>% 
  st_transform(eqdc)
st_geometry(conus)

#1.3
boundary_sf = st_as_sf(rnaturalearth::countries110, 
                      coords = c("X", "Y"), 
                      crs = 4326) %>% 
  filter(admin %in% c("Canada",
                            "United States of America",
                            "Mexico")) %>% 
  st_transform(eqdc)
st_geometry(boundary_sf)
plot(boundary_sf)

#1.4
cities=read_csv("../data/uscities.csv")
head(cities)
cities_sf=st_as_sf(cities,
                   coords=c("lng","lat"),
                   crs= 4326) %>% 
  filter(!state_name %in% c("Puerto Rico",
                            "Alaska",
                            "Hawaii")) %>% 
  st_cast("POINT") %>% 
  select(city, state_name, county_name, population) %>% 
  st_transform(eqdc)
st_geometry(cities_sf)
```

### Question 2
```{r}
#2.1
us_u_ml = st_union(conus) %>%
  st_cast("MULTILINESTRING") 

cities_sf=mutate(cities_sf ,distance_to_usb = 
                   set_units(st_distance(cities_sf, 
                               us_u_ml), "km"))
st_geometry(us_u_ml)
farthest_from_border = cities_sf %>% 
  slice_max(distance_to_usb, n = 5) %>% 
  select(city, state_name, distance_to_usb) %>% 
  st_drop_geometry()

knitr::kable(farthest_from_border, 
             caption = "Furthest Cities From the US Border",
             col.names = c("City", "State", "Distance"),
             format.args = list(big.mark = ","))

#2.2
us_c_ml = st_combine(conus) %>%
  st_cast("MULTILINESTRING") 

cities_sf=mutate(cities_sf ,distance_to_stateb = 
                   set_units(st_distance(cities_sf, 
                               us_c_ml), "km"))
st_geometry(us_c_ml)

farthest_from_stateborder = cities_sf %>% 
  slice_max(distance_to_stateb, n = 5) %>% 
  select(city, state_name, distance_to_stateb) %>% 
  st_drop_geometry()

knitr::kable(farthest_from_stateborder, 
             caption = "Furthest Cities From a State Border",
             col.names = c("City", "State", "Distance"),
             format.args = list(big.mark = ","))

#2.3
mexican_border=boundary_sf %>% 
  filter(admin %in% "Mexico") %>% 
  st_combine() %>% 
  st_cast("MULTILINESTRING")

cities_sf=mutate(cities_sf ,distance_to_mexico = 
                   set_units(st_distance(cities_sf, 
                               mexican_border), "km"))

farthest_from_mexico = cities_sf %>% 
  slice_max(distance_to_mexico, n = 5) %>% 
  select(city, state_name, distance_to_mexico) %>% 
  st_drop_geometry()

knitr::kable(farthest_from_mexico, 
             caption = "Furthest Cities From the US-Mexico Border",
             col.names = c("City", "State", "Distance"),
             format.args = list(big.mark = ","))

#2.4
canadian_border=boundary_sf %>% 
  filter(admin %in% "Canada") %>% 
  st_combine() %>% 
  st_cast("MULTILINESTRING")

cities_sf=mutate(cities_sf ,distance_to_canada = 
                   set_units(st_distance(cities_sf, 
                               canadian_border), "km"))

farthest_from_canada = cities_sf %>% 
  slice_max(distance_to_canada, n = 5) %>% 
  select(city, state_name, distance_to_canada) %>% 
  st_drop_geometry()

knitr::kable(farthest_from_canada, 
             caption = "Furthest Cities From the US-Canada Border",
             col.names = c("City", "State", "Distance"),
             format.args = list(big.mark = ","))
```

### Question 3
```{r}
#3.1
ggplot() + 
  geom_sf(data = canadian_border, lty = 1, size = 1, color = "red") +
  geom_sf(data = mexican_border,lty = 1, size = 1, color = "green") +
  geom_sf(data = us_u_ml,lty = 1, size = 1, color = "blue") +
  geom_sf(data = us_c_ml, lty = 3)+
  geom_sf(data = (cities_sf %>% 
                    slice_max(population, n = 10)), 
                  size = 2, color = "red") +
  ggrepel::geom_label_repel(
    data = (cities_sf %>% 
                    slice_max(population, n = 10)),
    aes(label = city, geometry = geometry),
    stat = "sf_coordinates",
    size = 2) +
  ggthemes::theme_map() 

#3.2
ggplot() + 
  geom_sf(data = us_u_ml, size = 1, fill = "NA") +
  geom_sf(data = drop_units(cities_sf), aes(color = distance_to_usb), size = .5) + 
  scale_color_gradient(low = 'darkgreen', high = "orange") +
  ggrepel::geom_label_repel(
    data = (cities_sf %>% 
                    slice_max(distance_to_usb, n = 5)),
    aes(label = city, geometry = geometry),
    stat = "sf_coordinates",
    size = 3) +
  ggthemes::theme_map() 

#3.3
ggplot() + 
  geom_sf(data = us_c_ml, 
          size = 1, 
          fill = "NA") +
  geom_sf(data = drop_units(cities_sf), 
          aes(color = distance_to_stateb), 
          size = 1) + 
  scale_color_gradient(low = 'darkgreen', 
                       high = "orange") +
  ggrepel::geom_label_repel(
    data = (cities_sf %>% 
                    slice_max(distance_to_stateb, n = 5)),
    aes(label = city, geometry = geometry),
    stat = "sf_coordinates",
    size = 3) +
  ggthemes::theme_map() 

#3.4
cities_sf= mutate(cities_sf, equidistance= abs(distance_to_mexico-distance_to_canada))

ggplot()+
  geom_sf(data = us_u_ml, size = 1, fill = "NA")+
  geom_sf(data = drop_units(cities_sf), 
          aes(color = equidistance), 
          size = .5)+
  scale_color_gradient(low = 'red', high = "blue") +
  gghighlight(equidistance < 100) +
  ggrepel::geom_label_repel(
    data = (drop_units(cities_sf) %>% 
              filter(equidistance < 100) %>% 
              slice_max(population, n = 5)),
    aes(label = city, geometry = geometry),
    stat = "sf_coordinates",
    size = 3) +
  ggthemes::theme_map() 
```

### Question 4
```{r}

```

